### ISSUE TITLE
Running on Ubuntu and MacOs

### ISSUE THREAD

**Issue by SeJohnEff** [keylime/ansible-keylime-tpm-emulator#49]
Hi I have run ansible Keylime-emulator almost successfully and found some issues. I'll maybe submit more. below is what I had to do to make it run. (this is my first issue submit to GitHub)

#vagrant macOS https://www.vagrantup.com/downloads
```
git clone https://github.com/keylime/ansible-keylime-tpm-emulator.git
git clone https://github.com/keylime/keylime.git
```
#edit vagrantfile change Fedora version 31 32, change ssh… to virtualbox
#edit playbook.yaml # - ansible-keylime-user
```
cd /Users/xxxxx/ansible-keylime-tpm-emulator
vagrant --instances=1 --repo=/Users/xxxx/keylime --cpus=1 --memory=4096  up --provider virtualbox --provision
```
#vagrant destroy, is a good command
`vagrant ssh
`#$
```
sudo pip install future
sudo pip install asn1 
sudo keylime_verifier
sudo keylime_registrar
sudo keylime_agent
sudo keylime_node 
```

verifier, registrar & agent starts up fine.
I had to do same edits when running on Ubuntu

Love your work.
Good things,
John

**Comment by SeJohnEff** [comment]
Thanks! Vagrant file updated. Yey!

**Comment by SeJohnEff** [comment]
and playbook! thanks again!

**Comment by lukehinds** [comment]
is this working ok now?

**Comment by SeJohnEff** [comment]
specifically this part works, yes.
I take it step by step.
thanks for super quick fix

**Comment by SeJohnEff** [comment]
This is working now
